// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
	"kratos-blog/internal/biz"
	"kratos-blog/internal/conf"
	"kratos-blog/internal/data"
	"kratos-blog/internal/server"
	"kratos-blog/internal/service"
	"kratos-blog/pkg/database"
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(confServer *conf.Server, confData *conf.Data, logger log.Logger) (*kratos.App, func(), error) {
	db, err := database.NewDB(confData)
	if err != nil {
		return nil, nil, err
	}
	dataData, cleanup, err := data.NewData(logger, db)
	if err != nil {
		return nil, nil, err
	}
	articleRepo := data.NewArticleRepo(dataData, logger)
	articleUsercase := biz.NewArticleUsercase(articleRepo, logger)
	blogService := service.NewBlogService(articleUsercase, logger)
	grpcServer := server.NewGRPCServer(confServer, blogService, logger)
	httpServer := server.NewHTTPServer(confServer, blogService, logger)
	app := newApp(logger, grpcServer, httpServer)
	return app, func() {
		cleanup()
	}, nil
}
